[project]
name = "html2text"
version = "0.1.0"
dependencies = [
    "attrs>=24.2.0",
    "selectolax>=0.3.24",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
